"""add search_vector column to tutors

Revision ID: 316e847215ba
Revises: e4add6f1c6e5
Create Date: 2026-03-04 01:57:11.117236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '316e847215ba'
down_revision = 'e4add6f1c6e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('search_vector', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutors', schema=None) as batch_op:
        batch_op.drop_column('search_vector')

    # ### end Alembic commands ###
