"""add payment model and stripe fields to tutor

Revision ID: 43cb62dfbfa7
Revises: b081ebd607a6
Create Date: 2026-03-05 06:14:21.309647

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '43cb62dfbfa7'
down_revision = 'b081ebd607a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_account_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('stripe_onboarding_complete', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutors', schema=None) as batch_op:
        batch_op.drop_column('stripe_onboarding_complete')
        batch_op.drop_column('stripe_account_id')

    # ### end Alembic commands ###
