"""Add guardian dashboard fields and booking guardian_approved

Revision ID: 7cb9bee658d4
Revises: e954c5a04e53
Create Date: 2026-03-05 06:54:48.170431

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '7cb9bee658d4'
down_revision = 'e954c5a04e53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guardian_approved', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('guardian_approved_on', sa.DateTime(), nullable=True))

    with op.batch_alter_table('guardians', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('notification_prefs', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guardians', schema=None) as batch_op:
        batch_op.drop_column('last_login')
        batch_op.drop_column('notification_prefs')
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('guardian_approved_on')
        batch_op.drop_column('guardian_approved')

    # ### end Alembic commands ###
