"""add timezone to student tutor admin models

Revision ID: b081ebd607a6
Revises: 316e847215ba
Create Date: 2026-03-05 06:09:31.145496

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b081ebd607a6'
down_revision = '316e847215ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timezone', sa.String(length=50), nullable=True))

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timezone', sa.String(length=50), nullable=True))

    with op.batch_alter_table('tutors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timezone', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutors', schema=None) as batch_op:
        batch_op.drop_column('timezone')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('timezone')

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_column('timezone')

    # ### end Alembic commands ###
