"""Add chat blocking and started_by fields

Revision ID: e11cb66c5806
Revises: 823251ab49d7
Create Date: 2026-03-05 08:07:10.965605

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e11cb66c5806'
down_revision = '823251ab49d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('started_by', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('is_blocked_by_student', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_blocked_by_tutor', sa.Boolean(), nullable=True))
        batch_op.create_unique_constraint('uq_conversation_pair', ['student_id', 'tutor_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_constraint('uq_conversation_pair', type_='unique')
        batch_op.drop_column('is_blocked_by_tutor')
        batch_op.drop_column('is_blocked_by_student')
        batch_op.drop_column('started_by')

    # ### end Alembic commands ###
